LaTeX handling

diff --git a/mpl/Makefile b/mpl/Makefile
--- a/mpl/Makefile
+++ b/mpl/Makefile
@@ -17,22 +17,30 @@ include ${MAKEINCLUDES}/Make.cmake
 include ${MAKEINCLUDES}/Make.cbuild
 info ::
 	@echo "make docs : doxygen html & latex docs"
+	@echo "    [ LATEXDOC=0/1 (default=${LATEXDOC}) ]"
 .PHONY: docs
-LATEXDOC=NO
+LATEXDOC=0
 docs :
 	@source ${MAKEINCLUDES}/names.sh \
 	 && export MODE=${MODE} && export INSTALLROOT=${INSTALLROOT} \
 	 && setnames ${PACKAGEROOT} ${PACKAGE} ${PACKAGEVERSION} ${INSTALLEXT} \
 	 && cd $${builddir}/doc/doxygen \
 	 && doctarget=$${installdir}/../docs-${PACKAGEVERSION} \
+	 && if "${LATEXDOC}" = "1" ] ; then \
+	        LATEXYESNO=YES ; else LATEXYESNO=NO ; fi \
+	 && ( cat Doxyfile && echo GENERATE_LATEX=${LATEXYESNO} ) | doxygen - \
+	 && if [ "${LATEXDOC}" = "1" ] ; then \
+	      ( cd latex \
+	        && yes | tr y q | pdflatex refman || echo "skip errors" \
+	        && yes | tr y q | pdflatex refman || echo "skip errors" \
+	      ) ; fi \
 	 && mkdir -p $$doctarget \
-	 && ( cat Doxyfile && echo GENERATE_LATEX=${LATEXDOC} ) | doxygen - \
-	 && if [ "${LATEXDOC}" = "YES" ] ; then \
-	      ( cd latex && pdflatex refman && pdflatex refman  ) ; fi \
 	 && for t in html latex ; do \
-	      if [ -d $${doctarget}/$$t ] ; then \
-	        rm -rf $${doctarget}/$$t ; fi \
-	       && cp -r $$t $${doctarget}/ \
+	      if [ -d $$t ] ; then \
+	        if [ -d $${doctarget}/$$t ] ; then \
+	          rm -rf $${doctarget}/$$t ; fi \
+	         && cp -r $$t $${doctarget}/ \
+	      ; fi \
 	    ; done
 
 GITREPO = git@github.com:rabauke/mpl.git
